version: "3.8"

services:
  terraform_aws_vpn:
    container_name: terraform_aws_vpn
    image: terraform_aws_vpn
    platform: linux/amd64
    build:
      context: ./
    volumes:
        # ユーザー作成をする際に、/home/vscodeディレクトリに
        # .sshなどのディレクトリが自動で作成されるのでマウントできない。
        - ../:/home/vscode/workspaces:cached
    entrypoint: "/bin/sh"
    env_file:
      - ../.env
    tty: true
    # working_dir: /home/vscode/workspaces
